name: Check Markdown links
on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.11
        with:
          folder-path: "docs"
